"""
Generate dnf_gl_procaddr.{h,cpp}: SDL_GL_GetProcAddress replacement for vitaGL.

WHY: EDuke32 loads every GL function through glad function pointers fed by
SDL_GL_GetProcAddress. SDL1-Vita implements no GL, but vitaGL links its GL
symbols statically - so we resolve names to &glFunction addresses at build
time by parsing the INSTALLED vitaGL headers ($VITASDK/.../include/GL/).

Usage:
    python3 gen_gl_procaddr.py <vitasdk-gl-include-dir> <out-dir>

Output:
    <out-dir>/dnf_gl_procaddr.h    -> void *DNF_GL_GetProcAddress(const char *);
    <out-dir>/dnf_gl_procaddr.cpp  -> strcmp chain over every gl* declaration.
"""
import os
import re
import sys

FUNC_RE = re.compile(r'\b(gl[A-Za-z0-9]+)\s*\(')


def collect_functions(include_dir):
    funcs = []
    seen = set()
    if not os.path.isdir(include_dir):
        print(f"  ERROR: GL include dir not found: {include_dir}")
        print("  Install vitaGL first (vdpm vitagl) with VitaSDK set up.")
        sys.exit(1)
    for fname in sorted(os.listdir(include_dir)):
        if not fname.endswith('.h'):
            continue
        with open(os.path.join(include_dir, fname), 'r', errors='replace') as f:
            for line in f:
                s = line.strip()
                # skip comments / preprocessor / typedefs
                if not s or s.startswith(('#', '/', '*', 'typedef')):
                    continue
                m = FUNC_RE.search(s)
                if m and m.group(1) not in seen:
                    seen.add(m.group(1))
                    funcs.append(m.group(1))
    return funcs


def generate(include_dir, out_dir):
    funcs = collect_functions(include_dir)
    if not funcs:
        print(f"  ERROR: no GL functions parsed from {include_dir}")
        sys.exit(1)

    os.makedirs(out_dir, exist_ok=True)

    with open(os.path.join(out_dir, 'dnf_gl_procaddr.h'), 'w') as f:
        f.write('#pragma once\n'
                '// Generated by gen_gl_procaddr.py - do not edit.\n'
                '#ifdef __cplusplus\nextern "C" {\n#endif\n'
                'void *DNF_GL_GetProcAddress(const char *name);\n'
                '#ifdef __cplusplus\n}\n#endif\n')

    with open(os.path.join(out_dir, 'dnf_gl_procaddr.cpp'), 'w') as f:
        f.write('// Generated by gen_gl_procaddr.py - do not edit.\n'
                '#include <string.h>\n'
                '#include <vitaGL.h>\n'
                '#include "dnf_gl_procaddr.h"\n\n'
                'void *DNF_GL_GetProcAddress(const char *name)\n'
                '{\n'
                '    if (!name) return 0;\n')
        for fn in funcs:
            f.write(f'    if (!strcmp(name, "{fn}")) return (void*)&{fn};\n')
        f.write('    return 0;\n}\n')

    print(f"  Generated dnf_gl_procaddr with {len(funcs)} GL symbols")


if __name__ == '__main__':
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <vitasdk-gl-include-dir> <out-dir>")
        sys.exit(1)

    generate(sys.argv[1], sys.argv[2])
