"""
Patch EDuke32-Vita for the EXPERIMENTAL vitaGL renderer (DNF_VITA_GL=1 builds).

WHAT IT DOES (all inside #ifdef DNF_VITA_GL, stable 8-bit build untouched):
  1. Common.mak: PSP2 USE_OPENGL becomes conditional (1 when DNF_VITA_GL=1),
     plus -DDNF_VITA_GL in COMPILERFLAGS.
  2. GNUmakefile: compile dnf_gl_procaddr.cpp (generated by gen_gl_procaddr.py)
     and link -lvitaGL, only when DNF_VITA_GL=1.
  3. sdlayer12.cpp: vitaGL includes at top; videoSetMode() forces the vitaGL
     path (320x200x32 + glad loader fed by DNF_GL_GetProcAddress +
     setrendermode(REND_POLYMOST)) because SDL1-Vita implements no GL context.
  4. sdlayer.cpp: vitaGL include for PSP2; videoShowFrame() presents via
     vglSwapBuffers when running Polymost.

REQUIRES: separate build dir (build_vita.sh clones build_eduke32_gl), vitaGL
installed (vdpm vitagl), generated dnf_gl_procaddr.{h,cpp} in
source/build/src/ (see gen_gl_procaddr.py).

STATUS: experimental - needs hardware testing (see README "Renderer GPU").
"""
import sys


def _need(content, needle, label, filepath):
    if needle not in content:
        print(f"    [FAIL] {label} not found in {filepath}!")
        sys.exit(1)


def patch_glrenderer(build_dir):
    import os

    sdlayer12 = os.path.join(build_dir, 'source/build/src/sdlayer12.cpp')
    sdlayer = os.path.join(build_dir, 'source/build/src/sdlayer.cpp')
    common = os.path.join(build_dir, 'Common.mak')
    gnumake = os.path.join(build_dir, 'GNUmakefile')

    for p in (sdlayer12, sdlayer, common, gnumake):
        with open(p) as f:
            if 'DNF_VITA_GL' in f.read():
                print(f"  {p} GL already patched, skipping.")
                return

    # --- 1. Common.mak: conditional USE_OPENGL for PSP2 ---
    with open(common) as f:
        mk = f.read()
    old_use = ('else ifeq ($(PLATFORM),PSP2)\n'
               '    override USE_OPENGL := 0\n')
    new_use = ('else ifeq ($(PLATFORM),PSP2)\n'
               '    ifeq ($(DNF_VITA_GL),1)\n'
               '        USE_OPENGL := 1\n'
               '        COMPILERFLAGS += -DDNF_VITA_GL\n'
               '    else\n'
               '        override USE_OPENGL := 0\n'
               '    endif\n')
    _need(mk, old_use, 'PSP2 USE_OPENGL block', common)
    mk = mk.replace(old_use, new_use, 1)
    with open(common, 'w') as f:
        f.write(mk)
    print("    [OK] Common.mak: USE_OPENGL conditional (DNF_VITA_GL=1)")

    # --- 2. GNUmakefile: generated TU + vitagl link ---
    with open(gnumake) as f:
        gm = f.read()
    old_objs = '    engine_objs += psp2_kbdvita.cpp\n'
    new_objs = ('    engine_objs += psp2_kbdvita.cpp\n'
                '    ifeq ($(DNF_VITA_GL),1)\n'
                '        engine_objs += dnf_gl_procaddr.cpp\n'
                '        LIBS += -lvitaGL\n'
                '    endif\n')
    _need(gm, old_objs, 'psp2_kbdvita engine_objs', gnumake)
    gm = gm.replace(old_objs, new_objs, 1)
    with open(gnumake, 'w') as f:
        f.write(gm)
    print("    [OK] GNUmakefile: dnf_gl_procaddr.cpp + -lvitaGL (DNF_VITA_GL=1)")

    # --- 3a. sdlayer12.cpp: includes ---
    with open(sdlayer12) as f:
        s12 = f.read()
    old_inc = '#include <SDL/SDL_events.h>\n'
    new_inc = ('#include <SDL/SDL_events.h>\n'
               '#ifdef DNF_VITA_GL\n'
               '#include <vitaGL.h>\n'
               '#include "dnf_gl_procaddr.h"\n'
               '#endif\n')
    _need(s12, old_inc, 'SDL_events include', sdlayer12)
    s12 = s12.replace(old_inc, new_inc, 1)
    print("    [OK] sdlayer12.cpp: vitaGL includes")

    # --- 3b. sdlayer12.cpp: videoSetMode forces vitaGL path ---
    old_sig = ('int32_t videoSetMode(int32_t x, int32_t y, int32_t c, int32_t fs)\n'
               '{\n'
               '    int32_t regrab = 0, ret;\n')
    gl_block = (
        '#ifdef DNF_VITA_GL\n'
        '    // EXPERIMENTAL vitaGL renderer: SDL1-Vita has no GL context,\n'
        '    // init vitaGL directly (480x272x32 + Polymost). See README.\n'
        '    {\n'
        '        extern void *DNF_GL_GetProcAddress(const char *);\n'
        '        nogl = 0;\n'
        '        vglInitExtended(0, 320, 200, 4*1024*1024, SCE_GXM_MULTISAMPLE_NONE);\n'
        '        initprintf("DNF_VITA_GL: vitaGL init 320x200\\n");\n'
        '        xres = xdim = 320; yres = ydim = 200; bpp = 32;\n'
        '        fullscreen = fs; bytesperline = 320; numpages = 1; lockcount = 0;\n'
        '        modechange = 1; videomodereset = 0;\n'
        '        sdl_surface = (SDL_Surface *)0x1;\n'
        '        gladLoadGLLoader((GLADloadproc)DNF_GL_GetProcAddress);\n'
        '        setrendermode(REND_POLYMOST);\n'
        '        setvideomode_sdlcommonpost(xres, yres, 32, fs, regrab);\n'
        '        return 0;\n'
        '    }\n'
        '#endif\n'
    )
    _need(s12, old_sig, 'videoSetMode signature', sdlayer12)
    s12 = s12.replace(old_sig, old_sig + gl_block, 1)
    with open(sdlayer12, 'w') as f:
        f.write(s12)
    print("    [OK] sdlayer12.cpp: videoSetMode vitaGL path (480x272 Polymost)")

    # --- 4a. sdlayer.cpp: vitaGL include for PSP2 ---
    with open(sdlayer) as f:
        sl = f.read()
    old_v2d = '#include <vita2d.h>\n'
    new_v2d = ('#include <vita2d.h>\n'
               '#ifdef DNF_VITA_GL\n'
               '#include <vitaGL.h>\n'
               '#endif\n')
    _need(sl, old_v2d, 'vita2d include', sdlayer)
    sl = sl.replace(old_v2d, new_v2d, 1)
    print("    [OK] sdlayer.cpp: vitaGL include")

    # --- 4b. sdlayer.cpp: present via vitaGL under Polymost ---
    old_show = ('void videoShowFrame(int32_t w)\n'
                '{\n'
                '    UNREFERENCED_PARAMETER(w);\n'
                '\n'
                '    if (offscreenrendering) return;\n')
    new_show = (old_show +
                '#ifdef DNF_VITA_GL\n'
                '    if (getrendermode() >= REND_POLYMOST) { vglSwapBuffers(1); return; }\n'
                '#endif\n')
    _need(sl, old_show, 'videoShowFrame head', sdlayer)
    sl = sl.replace(old_show, new_show, 1)
    with open(sdlayer, 'w') as f:
        f.write(sl + '\n// DNF_VITA_GL applied\n')
    print("    [OK] sdlayer.cpp: videoShowFrame vglSwapBuffers under Polymost")

    print("\n  GL renderer patch applied (DNF_VITA_GL build only)")


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <build_dir>")
        sys.exit(1)

    patch_glrenderer(sys.argv[1])
